version: "3.6"
   
services:

  web:
    environment:
      - SECRET_KEY=sample_secret_key
      - HOST="*"
      - DB_TYPE=sqlite3
      - DEBUG=True
      - MOCK_SMS_EMAIL=True
      - AWS_SECRET_ACCESS_KEY='your_aws_secret_access_key'
      - AWS_ACCESS_KEY_ID='your_aws_access_key_id'
      - PYTHONDONTWRITEBYTECODE=1
    build: .
<<<<<<< HEAD
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py test && python manage.py runserver 0.0.0.0:5000"
=======
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py test && python3 manage.py runserver 0.0.0.0:3000"
>>>>>>> 582d8a2816d6bf24a1b2a84e36658656c443627f

    volumes:
      - .:/code
    ports:
      - "5000:5000"
    
